apiVersion: apps/v1
kind: Deployment
metadata:
    name: todo-app-dep
    namespace: project-namespace
spec:
    replicas: 1
    selector:
        matchLabels:
            app: todo-app
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: todo-app
        spec:
            volumes:
                - name: random-images
                  persistentVolumeClaim:
                      claimName: todo-app-claim
            containers:
                - name: todo-app
                  image: TODO-APP/IMAGE
                  env:
                      - name: PORT
                        value: "3003"
                  volumeMounts:
                      - name: random-images
                        mountPath: /usr/src/app/public/random_image
