apiVersion: v1
kind: Service
metadata:
    name: todo-app-svc
    namespace: project-namespace
spec:
    type: NodePort
    selector:
        app: todo-app # This is the app as declared in the deployment.
    ports:
        - port: 80
          protocol: TCP
          targetPort: 3003
