apiVersion: v1
kind: Service
metadata:
    name: project-svc
spec:
    type: ClusterIP
    selector:
        app: project # This is the app as declared in the deployment.
    ports:
        - port: 2345
          protocol: TCP
          targetPort: 3003
