apiVersion: apps/v1
kind: Deployment
metadata:
    name: log-output-dep
    namespace: exercises-namespace
spec:
    replicas: 1
    selector:
        matchLabels:
            app: log-output
    template:
        metadata:
            labels:
                app: log-output
        spec:
            volumes:
                - name: shared-timestamp
                  emptyDir: {}
                - name: config
                  configMap:
                      name: log-output-configmap
                      items:
                          - key: "serverconfig.txt"
                            path: "serverconfig.txt"
            containers:
                - name: log-output-reader
                  image: ktatu/log-output-reader:2.11
                  env:
                      - name: PORT
                        value: "3002"
                      - name: PINGS_URL
                        value: "http://pong-svc:80/pingpong"
                      - name: MESSAGE
                        valueFrom:
                            configMapKeyRef:
                                name: log-output-configmap
                                key: message
                  volumeMounts:
                      - name: shared-timestamp
                        mountPath: /usr/src/app/files/timestamp
                      - name: config
                        mountPath: "/usr/src/app/files/config"
                        readOnly: true
                - name: log-output-generator
                  image: ktatu/log-output-generator:1.1
                  volumeMounts:
                      - name: shared-timestamp
                        mountPath: /usr/src/app/files/timestamp
