apiVersion: apps/v1
kind: Deployment
metadata:
    name: todo-backend-dep
spec:
    replicas: 1
    selector:
        matchLabels:
            app: todo-backend
    template:
        metadata:
            labels:
                app: todo-backend
        spec:
            containers:
                - name: project
                  image: ktatu/todo-backend
                  env:
                      - name: PORT
                        value: "3000"
