apiVersion: apps/v1
kind: Deployment
metadata:
    name: todo-backend-dep
    namespace: project-namespace
spec:
    replicas: 1
    selector:
        matchLabels:
            app: todo-backend
    template:
        metadata:
            labels:
                app: todo-backend
        spec:
            containers:
                - name: project
                  image: ktatu/todo-backend:2.13
                  env:
                      - name: PORT
                        value: "3000"
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: postgres-vars
                                key: POSTGRES_PASSWORD
                      - name: POSTGRES_HOST
                        valueFrom:
                            secretKeyRef:
                                name: postgres-vars
                                key: POSTGRES_HOST
