apiVersion: batch/v1
kind: CronJob
metadata:
    name: hourly-todo
    namespace: project-namespace
spec:
    schedule: "0 * * * *"
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                        - name: hourly-todo
                          image: ktatu/hourly-todo:2.1
                          env:
                              - name: POSTGRES_PASSWORD
                                valueFrom:
                                    secretKeyRef:
                                        name: postgres-vars
                                        key: POSTGRES_PASSWORD
                              - name: POSTGRES_HOST
                                valueFrom:
                                    secretKeyRef:
                                        name: postgres-vars
                                        key: POSTGRES_HOST
                    restartPolicy: Never
