apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: todo-app-claim # name of ther volume claim, this will be used in the deployment
    namespace: project-namespace
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 1Gi
