apiVersion: v1
kind: Secret
metadata:
    name: postgres-password
    namespace: exercises-namespace
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:uN0rdztz45hZbcNesrDU8g==,iv:kadoIACRt3JLexn5HGCTdg4Gj1N/pkDy+NGIM86FApY=,tag:lYOhkv5nf0Mm0l+c70eegA==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:btWJYd6V/v9W17GLab/ljQ==,iv:4tpihmiw/itROw/+hfneoqmS1ikwqAfPke/J0AbFPa8=,tag:sQUVUv2qxp+qtiI3onAjXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8y4d30j25j8zjzqfuet4jlepw04jlwqt8d2zsj5r8dm6c3prd7qc22xzw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUTFkaHZtaVlibm5ZbGJR
            NnZNQ3hBYlk4T04zbjZzUk9scWRNaEJDbml3CjZiZWYzVjdZcTQwYldKSGhEbXhi
            U3lsaGd0RmZFakd6VUZiMHdEei9HVUUKLS0tIG5EcXhOZjRMSGQ3cEtYeDhtQ2lt
            VjE5RDRXRnF6cE0xTjFXWFhWZm1JUkEK2f3ubXihuVCWztVqLX02NPYLyk0P5ghV
            /VpYoNMpaliZzepHJnMNNSRudGhm82ERwPQ4uFrsIFzD74JNtHNvFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-20T15:50:23Z"
    mac: ENC[AES256_GCM,data:R0B2imSOikD6jW8emLkD3RJPB4kUs6xrqNNoHZ/yHfw4CQQRpzZyh1nYaJRtgh9HKxdIVPb+EH8Z26z843AEoKzupR6OV6/bWTqpv/j8G4wwoRwuNctmlxSdRCY0udFY9e/e/rbOC7/8iddNtemSrkuA8xAiVkZ2geE6hs/IjVI=,iv:385NxbdUxKRJsn3/+quR4TeVqWjIkLw4nugps/sxSws=,tag:57SvBdzLnaOldy96bSCSEA==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.0
