apiVersion: apps/v1
kind: Deployment
metadata:
    name: pong-dep
    namespace: exercises-namespace
spec:
    replicas: 1
    selector:
        matchLabels:
            app: pong
    template:
        metadata:
            labels:
                app: pong
        spec:
            containers:
                - name: pong
                  image: ktatu/pong:2.10
                  env:
                      - name: PORT
                        value: "3000"
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: postgres-password
                                key: POSTGRES_PASSWORD
                      - name: POSTGRES_HOST
                        valueFrom:
                            secretKeyRef:
                                name: postgres-password
                                key: POSTGRES_HOST
