apiVersion: v1
kind: Service
metadata:
    name: pong-svc
    namespace: exercises-namespace
spec:
    type: NodePort
    selector:
        app: pong
    ports:
        - port: 80
          protocol: TCP
          targetPort: 3000
