apiVersion: v1
kind: Service
metadata:
    name: pong-svc
    namespace: exercises-namespace
spec:
    type: ClusterIP
    selector:
        app: pong
    ports:
        - port: 2345
          protocol: TCP
          targetPort: 3000
