name: Delete Environment

on:
    delete:
    workflow_dispatch:

env:
    PROJECT_ID: ${{ secrets.PROJECT_ID }}
    GKA_SA_KEY: ${{ secrets.GOOGLE_CREDENTIALS }}
    GKE_CLUSTER: dwk-cluster
    GKE_ZONE: europe-north1-b

jobs:
    delete:
        if: github.event.ref_type == 'branch'
        defaults:
            run:
                working-directory: ./project
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: google-github-actions/auth@v2
              with:
                  credentials_json: "${{ env.GKA_SA_KEY }}"

            - name: "Set up Cloud SDK"
              uses: google-github-actions/setup-gcloud@v2

            - name: "Use gcloud CLI"
              run: gcloud info
            - run: gcloud --quiet auth configure-docker

            - name: "Get GKE credentials"
              uses: "google-github-actions/get-gke-credentials@v2"
              with:
                  cluster_name: "${{ env.GKE_CLUSTER }}"
                  project_id: "${{ env.PROJECT_ID }}"
                  location: "${{ env.GKE_ZONE }}"

            - name: Delete environment
              run: kubectl delete namespace ${{ github.event.ref }}
